version: '3.8'

services:
  # Development environment - use this during development
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
    networks:
      - frs_network

  # Production environment - use this for deployment
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:DefinedAtTheDisco01*@frs-db.ch88c4s48jz3.eu-north-1.rds.amazonaws.com:5432/FRS
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=info
    restart: always
    networks:
      - frs_network

networks:
  frs_network:
    driver: bridge 