version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
    volumes:
      - .:/app
    networks:
      - frs_network

volumes:
  postgres_data:

networks:
  frs_network:
    driver: bridge 